### ISSUE TITLE
about ud-sender

### ISSUE THREAD

**Issue by StarryVae** [efficient/rdma_bench#5]
Hello, I wish to get your help, when i try to use the ud-sender to measure throughput of outbound UD SENDs, i got an error "Failed to create SEND CQ", could you give me some advice? thanks.

**Comment by anujkaliaiitd** [comment]
Did you allocate huge pages and set unlimited SHM limits? The scripts set some Mellanox environment variables that force the use of huge pages for queues.

**Comment by StarryVae** [comment]
I have allocated huge pages by "echo 8192 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages", but how to set unlimited SHM limits?

**Comment by anujkaliaiitd** [comment]
```
sudo bash -c "echo kernel.shmmax = 9223372036854775807 >> /etc/sysctl.conf"
sudo bash -c "echo kernel.shmall = 1152921504606846720 >> /etc/sysctl.conf"
sudo sysctl -p /etc/sysctl.conf
```

**Comment by StarryVae** [comment]
I have run the commands you presented, but i still got the error "Failed to create SEND CQ". What's more, i can successfully run the rw-tput-sender and sender-scalability, but the ud-sender can not be run.

**Comment by anujkaliaiitd** [comment]
Are you using a Mellanox NIC, or from some other vendor? Please provide more hardware and software details. Some NIC vendors do not support UD QPs.

**Comment by StarryVae** [comment]
I am using mlx4_0 and MLNX_OFED_LINUX, and i am sure that this NIC vendor can support UD QPs since i have conducted other UD tests.

**Comment by anujkaliaiitd** [comment]
It works on my cluster with ConnectX-3 NICs, Intel Xeon 2450, Mellanox OFED 4.2, and Ubuntu 16.04.

Does any other UD code from this repository work on your setup? Do you get this problem on a public Emulab cluster (in case you have access)? Otherwise, your best bet might be to compare my code against your working UD code and narrow down the difference. For example, are any of the arguments to `create_cq` very different?

**Comment by StarryVae** [comment]
Thank you for your reply !
